source ~/.vim/bundles.vim

" encoding dectection
set fileencodings=utf-8,gb2312,gb18030,gbk,ucs-bom,cp936,latin1

" enable filetype dectection and ft specific plugin/indent
filetype plugin indent on

" enable syntax hightlight and completion
syntax on

"--------
" Vim UI
"--------
hi clear
if version > 580
    " no guarantees for version 5.8 and below, but this makes it stop
    " complaining
    hi clear
    if exists("syntax_on")
        syntax reset
    endif
endif
let g:colors_name="molokai"

if exists("g:molokai_original")
    let s:molokai_original = g:molokai_original
else
    let s:molokai_original = 0
endif


hi Boolean         guifg=#AE81FF
hi Character       guifg=#E6DB74
hi Number          guifg=#AE81FF
hi String          guifg=#E6DB74
hi Conditional     guifg=#F92672               gui=bold
hi Constant        guifg=#AE81FF               gui=bold
hi Cursor          guifg=#000000 guibg=#F8F8F0
hi iCursor         guifg=#000000 guibg=#F8F8F0
hi Debug           guifg=#BCA3A3               gui=bold
hi Define          guifg=#66D9EF
hi Delimiter       guifg=#8F8F8F
hi DiffAdd                       guibg=#13354A
hi DiffChange      guifg=#89807D guibg=#4C4745
hi DiffDelete      guifg=#960050 guibg=#1E0010
hi DiffText                      guibg=#4C4745 gui=italic,bold

hi Directory       guifg=#A6E22E               gui=bold
hi Error           guifg=#E6DB74 guibg=#1E0010
hi ErrorMsg        guifg=#F92672 guibg=#232526 gui=bold
hi Exception       guifg=#A6E22E               gui=bold
hi Float           guifg=#AE81FF
hi FoldColumn      guifg=#465457 guibg=#000000
hi Folded          guifg=#465457 guibg=#000000
hi Function        guifg=#A6E22E
hi Identifier      guifg=#FD971F
hi Ignore          guifg=#808080 guibg=bg
hi IncSearch       guifg=#C4BE89 guibg=#000000

hi Keyword         guifg=#F92672               gui=bold
hi Label           guifg=#E6DB74               gui=none
hi Macro           guifg=#C4BE89               gui=italic
hi SpecialKey      guifg=#66D9EF               gui=italic

hi MatchParen      guifg=#000000 guibg=#FD971F gui=bold
hi ModeMsg         guifg=#E6DB74
hi MoreMsg         guifg=#E6DB74
hi Operator        guifg=#F92672

" complete menu
hi Pmenu           guifg=#66D9EF guibg=#000000
hi PmenuSel                      guibg=#808080
hi PmenuSbar                     guibg=#080808
hi PmenuThumb      guifg=#66D9EF

hi PreCondit       guifg=#A6E22E               gui=bold
hi PreProc         guifg=#A6E22E
hi Question        guifg=#66D9EF
hi Repeat          guifg=#F92672               gui=bold
hi Search          guifg=#000000 guibg=#FFE792
" marks
hi SignColumn      guifg=#A6E22E guibg=#232526
hi SpecialChar     guifg=#F92672               gui=bold
hi SpecialComment  guifg=#7E8E91               gui=bold
hi Special         guifg=#66D9EF guibg=bg      gui=italic
if has("spell")
    hi SpellBad    guisp=#FF0000 gui=undercurl
    hi SpellCap    guisp=#7070F0 gui=undercurl
    hi SpellLocal  guisp=#70F0F0 gui=undercurl
    hi SpellRare   guisp=#FFFFFF gui=undercurl
endif
hi Statement       guifg=#F92672               gui=bold
hi StatusLine      guifg=#455354 guibg=fg
hi StatusLineNC    guifg=#808080 guibg=#080808
hi StorageClass    guifg=#FD971F               gui=italic
hi Structure       guifg=#66D9EF
hi Tag             guifg=#F92672               gui=italic
hi Title           guifg=#ef5939
hi Todo            guifg=#FFFFFF guibg=bg      gui=bold

hi Typedef         guifg=#66D9EF
hi Type            guifg=#66D9EF               gui=none
hi Underlined      guifg=#808080               gui=underline

hi VertSplit       guifg=#808080 guibg=#080808 gui=bold
hi VisualNOS                     guibg=#403D3D
hi Visual                        guibg=#403D3D
hi WarningMsg      guifg=#FFFFFF guibg=#333333 gui=bold
hi WildMenu        guifg=#66D9EF guibg=#000000

hi TabLineFill     guifg=#1B1D1E guibg=#1B1D1E
hi TabLine         guibg=#1B1D1E guifg=#808080 gui=none

if s:molokai_original == 1
   hi Normal          guifg=#F8F8F2 guibg=#272822
   hi Comment         guifg=#75715E
   hi CursorLine                    guibg=#3E3D32
   hi CursorLineNr    guifg=#FD971F               gui=none
   hi CursorColumn                  guibg=#3E3D32
   hi ColorColumn                   guibg=#3B3A32
   hi LineNr          guifg=#BCBCBC guibg=#3B3A32
   hi NonText         guifg=#75715E
   hi SpecialKey      guifg=#75715E
else
   hi Normal          guifg=#F8F8F2 guibg=#1B1D1E
   hi Comment         guifg=#7E8E91
   hi CursorLine                    guibg=#293739
   hi CursorLineNr    guifg=#FD971F               gui=none
   hi CursorColumn                  guibg=#293739
   hi ColorColumn                   guibg=#232526
   hi LineNr          guifg=#465457 guibg=#232526
   hi NonText         guifg=#465457
   hi SpecialKey      guifg=#465457
end

"
" Support for 256-color terminal
"
if &t_Co > 255
   if s:molokai_original == 1
      hi Normal                   ctermbg=234
      hi CursorLine               ctermbg=235   cterm=none
      hi CursorLineNr ctermfg=208               cterm=none
   else
      hi Normal       ctermfg=252 ctermbg=233
      hi CursorLine               ctermbg=234   cterm=none
      hi CursorLineNr ctermfg=208               cterm=none
   endif
   hi Boolean         ctermfg=135
   hi Character       ctermfg=144
   hi Number          ctermfg=135
   hi String          ctermfg=144
   hi Conditional     ctermfg=161               cterm=bold
   hi Constant        ctermfg=135               cterm=bold
   hi Cursor          ctermfg=16  ctermbg=253
   hi Debug           ctermfg=225               cterm=bold
   hi Define          ctermfg=81
   hi Delimiter       ctermfg=241

   hi DiffAdd                     ctermbg=24
   hi DiffChange      ctermfg=181 ctermbg=239
   hi DiffDelete      ctermfg=162 ctermbg=53
   hi DiffText                    ctermbg=102 cterm=bold

   hi Directory       ctermfg=118               cterm=bold
   hi Error           ctermfg=219 ctermbg=89
   hi ErrorMsg        ctermfg=199 ctermbg=16    cterm=bold
   hi Exception       ctermfg=118               cterm=bold
   hi Float           ctermfg=135
   hi FoldColumn      ctermfg=67  ctermbg=16
   hi Folded          ctermfg=67  ctermbg=16
   hi Function        ctermfg=118
   hi Identifier      ctermfg=208               cterm=none
   hi Ignore          ctermfg=244 ctermbg=232
   hi IncSearch       ctermfg=193 ctermbg=16

   hi keyword         ctermfg=161               cterm=bold
   hi Label           ctermfg=229               cterm=none
   hi Macro           ctermfg=193
   hi SpecialKey      ctermfg=81

   hi MatchParen      ctermfg=233  ctermbg=208 cterm=bold
   hi ModeMsg         ctermfg=229
   hi MoreMsg         ctermfg=229
   hi Operator        ctermfg=161

   " complete menu
   hi Pmenu           ctermfg=81  ctermbg=16
   hi PmenuSel        ctermfg=255 ctermbg=242
   hi PmenuSbar                   ctermbg=232
   hi PmenuThumb      ctermfg=81

   hi PreCondit       ctermfg=118               cterm=bold
   hi PreProc         ctermfg=118
   hi Question        ctermfg=81
   hi Repeat          ctermfg=161               cterm=bold
   hi Search          ctermfg=0   ctermbg=222   cterm=NONE

   " marks column
   hi SignColumn      ctermfg=118 ctermbg=235
   hi SpecialChar     ctermfg=161               cterm=bold
   hi SpecialComment  ctermfg=245               cterm=bold
   hi Special         ctermfg=81
   if has("spell")
       hi SpellBad                ctermbg=52
       hi SpellCap                ctermbg=17
       hi SpellLocal              ctermbg=17
       hi SpellRare  ctermfg=none ctermbg=none  cterm=reverse
   endif
   hi Statement       ctermfg=161               cterm=bold
   hi StatusLine      ctermfg=238 ctermbg=253
   hi StatusLineNC    ctermfg=244 ctermbg=232
   hi StorageClass    ctermfg=208
   hi Structure       ctermfg=81
   hi Tag             ctermfg=161
   hi Title           ctermfg=166
   hi Todo            ctermfg=231 ctermbg=232   cterm=bold

   hi Typedef         ctermfg=81
   hi Type            ctermfg=81                cterm=none
   hi Underlined      ctermfg=244               cterm=underline

   hi VertSplit       ctermfg=244 ctermbg=232   cterm=bold
   hi VisualNOS                   ctermbg=238
   hi Visual                      ctermbg=235
   hi WarningMsg      ctermfg=231 ctermbg=238   cterm=bold
   hi WildMenu        ctermfg=81  ctermbg=16

   hi Comment         ctermfg=59
   hi CursorColumn                ctermbg=236
   hi ColorColumn                 ctermbg=236
   hi LineNr          ctermfg=250 ctermbg=236
   hi NonText         ctermfg=59

   hi SpecialKey      ctermfg=59

   if exists("g:rehash256") && g:rehash256 == 1
       hi Normal       ctermfg=252 ctermbg=234
       hi CursorLine               ctermbg=236   cterm=none
       hi CursorLineNr ctermfg=208               cterm=none

       hi Boolean         ctermfg=141
       hi Character       ctermfg=222
       hi Number          ctermfg=141
       hi String          ctermfg=222
       hi Conditional     ctermfg=197               cterm=bold
       hi Constant        ctermfg=141               cterm=bold

       hi DiffDelete      ctermfg=125 ctermbg=233

       hi Directory       ctermfg=154               cterm=bold
       hi Error           ctermfg=222 ctermbg=233
       hi Exception       ctermfg=154               cterm=bold
       hi Float           ctermfg=141
       hi Function        ctermfg=154
       hi Identifier      ctermfg=208

       hi Keyword         ctermfg=197               cterm=bold
       hi Operator        ctermfg=197
       hi PreCondit       ctermfg=154               cterm=bold
       hi PreProc         ctermfg=154
       hi Repeat          ctermfg=197               cterm=bold

       hi Statement       ctermfg=197               cterm=bold
       hi Tag             ctermfg=197
       hi Title           ctermfg=203
       hi Visual                      ctermbg=238

       hi Comment         ctermfg=244
       hi LineNr          ctermfg=239 ctermbg=235
       hi NonText         ctermfg=239
       hi SpecialKey      ctermfg=239
   endif
end
set background=dark

" highlight current line
au WinLeave * set nocursorline nocursorcolumn
au WinEnter * set cursorline cursorcolumn
set cursorline cursorcolumn

" search
set incsearch
"set highlight 	" conflict with highlight current line
set ignorecase
set smartcase

" editor settings
set history=1000
set nocompatible
set nofoldenable                                                  " disable folding"
set confirm                                                       " prompt when existing from an unsaved file
set backspace=indent,eol,start                                    " More powerful backspacing
set t_Co=256                                                      " Explicitly tell vim that the terminal has 256 colors "
set mouse=a                                                       " use mouse in all modes
set report=0                                                      " always report number of lines changed                "
set nowrap                                                        " dont wrap lines
set scrolloff=5                                                   " 5 lines above/below cursor when scrolling
set number                                                        " show line numbers
set showmatch                                                     " show matching bracket (briefly jump)
set showcmd                                                       " show typed command in status bar
set title                                                         " show file in titlebar
set laststatus=2                                                  " use 2 lines for the status bar
set matchtime=2                                                   " show matching bracket for 0.2 seconds
set matchpairs+=<:>                                               " specially for html
" set relativenumber

" Default Indentation
set autoindent
set smartindent     " indent when
set tabstop=4       " tab width
set softtabstop=4   " backspace
set shiftwidth=4    " indent width
" set textwidth=79
" set smarttab
set expandtab       " expand tab to space

autocmd FileType php setlocal tabstop=2 shiftwidth=2 softtabstop=2 textwidth=120
autocmd FileType ruby setlocal tabstop=2 shiftwidth=2 softtabstop=2 textwidth=120
autocmd FileType php setlocal tabstop=4 shiftwidth=4 softtabstop=4 textwidth=120
autocmd FileType coffee,javascript setlocal tabstop=2 shiftwidth=2 softtabstop=2 textwidth=120
autocmd FileType python setlocal tabstop=4 shiftwidth=4 softtabstop=4 textwidth=120
autocmd FileType html,htmldjango,xhtml,haml setlocal tabstop=2 shiftwidth=2 softtabstop=2 textwidth=0
autocmd FileType sass,scss,css setlocal tabstop=2 shiftwidth=2 softtabstop=2 textwidth=120

" syntax support
autocmd Syntax javascript set syntax=jquery   " JQuery syntax support
" js
let g:html_indent_inctags = "html,body,head,tbody"
let g:html_indent_script1 = "inc"
let g:html_indent_style1 = "inc"

"-----------------
" Plugin settings
"-----------------
" Rainbow parentheses for Lisp and variants
let g:rbpt_colorpairs = [
    \ ['brown',       'RoyalBlue3'],
    \ ['Darkblue',    'SeaGreen3'],
    \ ['darkgray',    'DarkOrchid3'],
    \ ['darkgreen',   'firebrick3'],
    \ ['darkcyan',    'RoyalBlue3'],
    \ ['darkred',     'SeaGreen3'],
    \ ['darkmagenta', 'DarkOrchid3'],
    \ ['brown',       'firebrick3'],
    \ ['gray',        'RoyalBlue3'],
    \ ['black',       'SeaGreen3'],
    \ ['darkmagenta', 'DarkOrchid3'],
    \ ['Darkblue',    'firebrick3'],
    \ ['darkgreen',   'RoyalBlue3'],
    \ ['darkcyan',    'SeaGreen3'],
    \ ['darkred',     'DarkOrchid3'],
    \ ['red',         'firebrick3'],
    \ ]
let g:rbpt_max = 16
autocmd Syntax lisp,scheme,clojure,racket RainbowParenthesesToggle

" tabbar
let g:Tb_MaxSize = 2
let g:Tb_TabWrap = 1

hi Tb_Normal guifg=white ctermfg=white
hi Tb_Changed guifg=green ctermfg=green
hi Tb_VisibleNormal ctermbg=252 ctermfg=235
hi Tb_VisibleChanged guifg=green ctermbg=252 ctermfg=white

" easy-motion
let g:EasyMotion_leader_key = '<Leader>'

" Tagbar
let g:tagbar_left=1
let g:tagbar_width=30
let g:tagbar_autofocus = 1
let g:tagbar_sort = 0
let g:tagbar_compact = 1
" tag for coffee
if executable('coffeetags')
  let g:tagbar_type_coffee = {
        \ 'ctagsbin' : 'coffeetags',
        \ 'ctagsargs' : '',
        \ 'kinds' : [
        \ 'f:functions',
        \ 'o:object',
        \ ],
        \ 'sro' : ".",
        \ 'kind2scope' : {
        \ 'f' : 'object',
        \ 'o' : 'object',
        \ }
        \ }

  let g:tagbar_type_markdown = {
    \ 'ctagstype' : 'markdown',
    \ 'sort' : 0,
    \ 'kinds' : [
        \ 'h:sections'
    \ ]
    \ }
endif

" Nerd Tree
let NERDChristmasTree=0
let NERDTreeWinSize=30
let NERDTreeChDirMode=2
let NERDTreeIgnore=['\~$', '\.pyc$', '\.swp$']
" let NERDTreeSortOrder=['^__\.py$', '\/$', '*', '\.swp$',  '\~$']
let NERDTreeShowBookmarks=1
let NERDTreeWinPos = "right"

" nerdcommenter
let NERDSpaceDelims=1
" nmap <D-/> :NERDComToggleComment<cr>
let NERDCompactSexyComs=1

" ZenCoding
let g:user_emmet_expandabbr_key='<C-j>'

" powerline
"let g:Powerline_symbols = 'fancy'

" SuperTab
" let g:SuperTabDefultCompletionType='context'
let g:SuperTabDefaultCompletionType = '<C-X><C-U>'
let g:SuperTabRetainCompletionType=2

" ctrlp
set wildignore+=*/tmp/*,*.so,*.o,*.a,*.obj,*.swp,*.zip,*.pyc,*.pyo,*.class,.DS_Store  " MacOSX/Linux
let g:ctrlp_custom_ignore = '\.git$\|\.hg$\|\.svn$'

" Keybindings for plugin toggle
nnoremap <F2> :set invpaste paste?<CR>
set pastetoggle=<F2>
nmap <F5> :TagbarToggle<cr>
nmap <F6> :NERDTreeToggle<cr>
nmap <F3> :GundoToggle<cr>
nmap <F4> :IndentGuidesToggle<cr>
nmap  <D-/> :
nnoremap <leader>a :Ack
nnoremap <leader>v V`]

"------------------
" Useful Functions
"------------------
" easier navigation between split windows
nnoremap <c-j> <c-w>j
nnoremap <c-k> <c-w>k
nnoremap <c-h> <c-w>h
nnoremap <c-l> <c-w>l

" When editing a file, always jump to the last cursor position
autocmd BufReadPost *
      \ if ! exists("g:leave_my_cursor_position_alone") |
      \     if line("'\"") > 0 && line ("'\"") <= line("$") |
      \         exe "normal g'\"" |
      \     endif |
      \ endif

" w!! to sudo & write a file
cmap w!! %!sudo tee >/dev/null %

" Quickly edit/reload the vimrc file
nmap <silent> <leader>ev :e $MYVIMRC<CR>
nmap <silent> <leader>sv :so $MYVIMRC<CR>

" sublime key bindings
nmap <D-]> >>
nmap <D-[> <<
vmap <D-[> <gv
vmap <D-]> >gv

" eggcache vim
nnoremap ; :
:command W w
:command WQ wq
:command Wq wq
:command Q q
:command Qa qa
:command QA qa

" for macvim
if has("gui_running")
    set go=aAce  " remove toolbar
    "set transparency=30
    set guifont=Monaco:h13
    set showtabline=2
    set columns=140
    set lines=40
    noremap <D-M-Left> :tabprevious<cr>
    noremap <D-M-Right> :tabnext<cr>
    map <D-1> 1gt
    map <D-2> 2gt
    map <D-3> 3gt
    map <D-4> 4gt
    map <D-5> 5gt
    map <D-6> 6gt
    map <D-7> 7gt
    map <D-8> 8gt
    map <D-9> 9gt
    map <D-0> :tablast<CR>
endif

"""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""
"""""新文件标题
""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""
"新建.c,.h,.sh,.java文件，自动插入文件头
autocmd BufNewFile *.cpp,*.[ch],*.pl,*.rb,*.sh,*.java,*.php,*.js,*.jsp,*.txt,*.sql,*.py,*.asm,*.[sS],Makefile exec ":call SetTitle()" 
""定义函数SetTitle，自动插入文件头
func SetTitle()
	"如果文件类型为.sh文件
	if &filetype == 'sh'
		call setline(1, "#\!/bin/bash")
		call append(line("."),"\#########################################################################") 
		call append(line(".")+1, "\# File Name: ".expand("%"))
		call append(line(".")+2, "\# Author:stevenzdg988")
		call append(line(".")+3, "\# mail:steven_zdg988@sina.com")
		call append(line(".")+4, "\# Created And Modified Time: ".strftime("====%Y-%m-%d  %H-%M-%S====")) 
		call append(line(".")+5, "\#########################################################################") 
		call append(line(".")+6, "")
	"elseif &filetype == 'py'
	elseif expand("%:e") == 'py'
		call setline(1,"#\!/usr/bin/python3")
		call append(line("."), "\#########################################################################")
		call append(line(".")+1,"\# File Name: ".expand("%"))
		call append(line(".")+2, "\# Author:stevenzdg988")
		call append(line(".")+3, "\# mail:steven_zdg988@sina.com")
		call append(line(".")+4, "\# Created And Modified Time: ".strftime("====%Y-%m-%d  %H-%M-%S====")) 
		call append(line(".")+5, "\#########################################################################")
		call append(line(".")+6, "")

	"elseif &filetype == 'perl'
	elseif expand("%:e") == 'pl'
		call setline(1,"#\!/usr/bin/perl")
		call append(line("."), "\#########################################################################")
		call append(line(".")+1,"\# File Name: ".expand("%"))
		call append(line(".")+2, "\# Author:stevenzdg988")
		call append(line(".")+3, "\# mail:steven_zdg988@sina.com")
		call append(line(".")+4, "\# Created And Modified Time: ".strftime("====%Y-%m-%d  %H-%M-%S====")) 
		call append(line(".")+5, "\#########################################################################")
		call append(line(".")+6, "")

	elseif expand("%:e") == 'rb'
		call setline(1,"#\!/usr/bin/ruby -w")
		call append(line("."), "\#########################################################################")
		call append(line(".")+1,"\# File Name: ".expand("%"))
		call append(line(".")+2, "\# Author:stevenzdg988")
		call append(line(".")+3, "\# mail:steven_zdg988@sina.com")
		call append(line(".")+4, "\# Created And Modified Time: ".strftime("====%Y-%m-%d  %H-%M-%S====")) 
		call append(line(".")+5, "\#########################################################################")
		call append(line(".")+6, "")

	"elseif &filetype == "php"
	elseif expand("%:e") == 'php'
		call setline(1, "<\?php")
		call append(line("."), "\/\*************************************************************************")
		call append(line(".")+1, "\* File Name:".expand("%"))
		call append(line(".")+2, "\* Author:stevenzdg988")
		call append(line(".")+3, "\* mail:steven_zdg988@sina.com")
		call append(line(".")+4, "\* Created And Modified Time:".strftime("====%Y-%m-%d  %H-%M-%S===="))
		call append(line(".")+5, "\************************************************************************\/")
		call append(line(".")+6, "")

	"elseif &filetype == "s"
	elseif expand("%:e") == 's'
		call setline(1, ";\/\*************************************************************************")
		call append(line("."), ";\* File Name:".expand("%"))
		call append(line(".")+1, ";\* Author:stevenzdg988")
		call append(line(".")+2, ";\* mail:steven_zdg988@sina.com")
		call append(line(".")+3, ";\* Created And Modified Time:".strftime("====%Y-%m-%d  %H-%M-%S===="))
		call append(line(".")+4, ";\************************************************************************\/")
		call append(line(".")+5, "")
	elseif expand("%:e") == 'asm'
		call setline(1, ";\/\*************************************************************************")
		call append(line("."), ";\* File Name:".expand("%"))
		call append(line(".")+1, ";\* Author:stevenzdg988")
		call append(line(".")+2, ";\* mail:steven_zdg988@sina.com")
		call append(line(".")+3, ";\* Created And Modified Time:".strftime("====%Y-%m-%d  %H-%M-%S===="))
		call append(line(".")+4, ";\************************************************************************\/")
		call append(line(".")+5, "")
	"elseif &filetype == "S"
	elseif expand("%:e") == 'S'
		call setline(1, ";\/\*************************************************************************")
		call append(line("."), ";\* File Name:".expand("%"))
		call append(line(".")+1, ";\* Author:stevenzdg988")
		call append(line(".")+2, ";\* mail:steven_zdg988@sina.com")
		call append(line(".")+3, ";\* Created And Modified Time:".strftime("====%Y-%m-%d  %H-%M-%S===="))
		call append(line(".")+4, ";\************************************************************************\/")
		call append(line(".")+5, "")

	elseif expand("%:e") == 'js'
		call setline(1, "//*************************************************************************") 
		call append(line("."), "//* File Name: ".expand("%"))
		call append(line(".")+1, "//* Author:stevenzdg988")
		call append(line(".")+2, "//* Mail:steven_zdg988@sina.com ")
		call append(line(".")+3, "//* Created And Modified Time: ".strftime("====%Y-%m-%d  %H-%M-%S====")) 
		call append(line(".")+4, "//*************************************************************************") 
		call append(line(".")+5, "")
	elseif expand("%:e") == 'java'
		call setline(1, "//*************************************************************************") 
		call append(line("."), "//* File Name: ".expand("%"))
		call append(line(".")+1, "//* Author:stevenzdg988")
		call append(line(".")+2, "//* Mail:steven_zdg988@sina.com ")
		call append(line(".")+3, "//* Created And Modified Time: ".strftime("====%Y-%m-%d  %H-%M-%S====")) 
		call append(line(".")+4, "//*************************************************************************") 
		call append(line(".")+5, "")
	elseif expand("%:e") == 'c'
		call setline(1, "//*************************************************************************") 
		call append(line("."), "//* File Name: ".expand("%"))
		call append(line(".")+1, "//* Author:stevenzdg988")
		call append(line(".")+2, "//* Mail:steven_zdg988@sina.com ")
		call append(line(".")+3, "//* Created And Modified Time: ".strftime("====%Y-%m-%d  %H-%M-%S====")) 
		call append(line(".")+4, "//*************************************************************************") 
		call append(line(".")+5, "")
	elseif expand("%:e") == 'cpp'
		call setline(1, "//*************************************************************************") 
		call append(line("."), "//* File Name: ".expand("%"))
		call append(line(".")+1, "//* Author:stevenzdg988")
		call append(line(".")+2, "//* Mail:steven_zdg988@sina.com ")
		call append(line(".")+3, "//* Created And Modified Time: ".strftime("====%Y-%m-%d  %H-%M-%S====")) 
		call append(line(".")+4, "//*************************************************************************") 
		call append(line(".")+5, "")
	elseif expand("%:e") == 'h'
		call setline(1, "//*************************************************************************") 
		call append(line("."), "//* File Name: ".expand("%"))
		call append(line(".")+1, "//* Author:stevenzdg988")
		call append(line(".")+2, "//* Mail:steven_zdg988@sina.com ")
		call append(line(".")+3, "//* Created And Modified Time: ".strftime("====%Y-%m-%d  %H-%M-%S====")) 
		call append(line(".")+4, "//*************************************************************************") 
		call append(line(".")+5, "")

	elseif expand("%:e") == 'jsp'
		call setline(1, "<%")
		call append(line("."),"//*************************************************************************") 
		call append(line(".")+1, "//* File Name: ".expand("%"))
		call append(line(".")+2, "//* Author:stevenzdg988")
		call append(line(".")+3, "//* Mail:steven_zdg988@sina.com ")
		call append(line(".")+4, "//* Created And Modified Time: ".strftime("====%Y-%m-%d  %H-%M-%S====")) 
		call append(line(".")+5, "//*************************************************************************") 
		call append(line(".")+6, "%>")
		call append(line(".")+7, " ")
	elseif expand("%:e") == 'txt'
		call setline(1, "//*************************************************************************") 
		call append(line("."), "//* File Name: ".expand("%"))
		call append(line(".")+1, "//* Author:stevenzdg988")
		call append(line(".")+2, "//* Mail:steven_zdg988@sina.com ")
		call append(line(".")+3, "//* Created And Modified Time: ".strftime("====%Y-%m-%d  %H-%M-%S====")) 
		call append(line(".")+4, "//*************************************************************************") 
		call append(line(".")+5, "")
	elseif expand("%:e") == 'sql'
		call setline(1, "//*************************************************************************") 
		call append(line("."), "//* File Name: ".expand("%"))
		call append(line(".")+1, "//* Author:stevenzdg988")
		call append(line(".")+2, "//* Mail:steven_zdg988@sina.com ")
		call append(line(".")+3, "//* Created And Modified Time: ".strftime("====%Y-%m-%d  %H-%M-%S====")) 
		call append(line(".")+4, "//*************************************************************************") 
		call append(line(".")+5, "")

	else
	"elseif &filetype == 'Makefile'
		call setline(1,"#\!Makefile")
		call append(line("."), "\#########################################################################")
		call append(line(".")+1,"\# File Name: ".expand("%"))
		call append(line(".")+2, "\# Author:stevenzdg988")
		call append(line(".")+3, "\# mail:steven_zdg988@sina.com")
		call append(line(".")+4, "\# Created And Modified Time: ".strftime("====%Y-%m-%d  %H-%M-%S====")) 
		call append(line(".")+5, "\#########################################################################")
		call append(line(".")+6, "")
	endif
	"if &filetype == 'cpp'
	if expand("%:e") == 'cpp'
		call append(line(".")+6, "\#include \<iostream\>")
		call append(line(".")+7, "using namespace std;")
		call append(line(".")+8, "int main() {")
		call append(line(".")+9, "")
		call append(line(".")+10, "    return 0;")
		call append(line(".")+11, "}")
	endif
	"if &filetype == 'c'
	if expand("%:e") == 'c'
		call append(line(".")+6, "\#include \"stdio.h\"")
		call append(line(".")+7, "int main(int argc, int argv[])\{")
		call append(line(".")+8, "      ")
		call append(line(".")+9, "    return 0;")
		call append(line(".")+10, "\}")
	endif
	"if &filetype == 'h'
	if expand("%:e") == "h"
		call append(line(".")+6, "\#ifndef _".toupper(expand("%:t:r"))."_H")
		call append(line(".")+7, "\#define _".toupper(expand("%:t:r"))."_H")
		call append(line(".")+8, "")
		call append(line(".")+9, "\#endif")
	endif
	"endif
	"if &filetype == 'java'
	if expand("%:e") == 'java'
		call append(line(".")+6, "import java.lang.*;")
		call append(line(".")+7,"public class ".expand("%:t:r")."{")
		call append(line(".")+8, "")
		call append(line(".")+9, "}")
	endif
	""if expand("%:e") == 'sh'
	""	call append(line(".")+5, "\#\!/bin/bash")
	""	call append(line(".")+6, "")
	""endif
	""if expand("%:e") == 'py'
	""	call append(line(".")+5, "\#\!/usr/bin/python")
	""	call append(line(".")+6, "")
	""endif
	if expand("%:e") == 'js'

	endif
	if expand("%:e") == 'jsp'

	endif
	if expand("%:e") == 'txt'

	endif
	if expand("%:e") == 'sql'

	endif
	"新建文件后，自动定位到文件末尾
	autocmd BufNewFile * normal 1G
endfunc
""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""
"键盘命令
""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""

nmap <leader>w :w!<cr>
nmap <leader>f :find<cr>

" 映射全选+复制 ctrl+a
map <C-A> ggVGY
map! <C-A> <Esc>ggVGY
map <F12> gg=G
" 选中状态下 Ctrl+c 复制
vmap <C-c> "+y
"去空行
nnoremap <F2> :g/^\s*$/d<CR>
"比较文件
nnoremap <C-F2> :vert diffsplit
"新建标签
map <M-F2> :tabnew<CR>
"列出当前目录文件
map <F3> :tabnew .<CR>
"打开树状文件目录
map <C-F3> \be
"C，C++ 按F5编译运行
map <F5> :call CompileRunGcc()<CR>
func! CompileRunGcc()
	exec "w"
	if &filetype == 'c'
		exec "!g++ % -o %<"
		exec "! ./%<"
	elseif &filetype == 'cpp'
		exec "!g++ % -o %<"
		exec "! ./%<"
	elseif &filetype == 'java'
		exec "!javac %"
		exec "!java %<"
	elseif &filetype == 'sh'
		:!./%
	elseif &filetype == 'py'
		exec "!python %"
		exec "!python %<"
	endif
	elseif &filetype == 'pl'
		exec "!perl %"
		"exec "!perl %<"
endfunc
"C,C++的调试
map <F8> :call Rungdb()<CR>
func! Rungdb()
	exec "w"
	exec "!g++ % -g -o %<"
	exec "!gdb ./%<"
endfunc
set nocompatible  "去掉讨厌的有关vi一致性模式，避免以前版本的一些bug和局限
" 显示中文帮助
if version >= 603
	set helplang=cn
	set encoding=utf-8
endif

"set nocompatible
"filetype off
"set rtp+=~/.vim/bundle/Vundle.vim
"call vundle#begin()
"Plugin 'gmarik/Vundle.vim'
"call vundle#end()
"filetype plugin indent on
