(write-line "helloWorld")
(defun fib (n)
  "Return the nth Fibonacci number."
  (if (< n 2)
      n
      (+ (fib (- n 1))
         (fib (- n 2)))))
(write(fib 20))
(write-line " ")
(defun functioname (m n)
  "Optional string"
  (/(+ m n) 2))
(write(functioname 10 20))

(print "Hello Lisp World!!")

(setq a 10)
(incf a 3)
(print a)
(decf a 3)
(print a)

(setq a 10)
(if (> a 20)
    (format t "~% a is lager than 20"))
   ;;then (format t "~% a is less than 20"))
(format t "~% value of a is ~d " a)

(print "****")
(write (/ 45 78))(terpri)
(write (floor 45 78))(terpri)
(write (/ 3456 75))(terpri)
(write (floor 3456 75))(terpri)
(write (ceiling 3456 75))(terpri)
(write (truncate 3456 75))(terpri)
(write (round 3456 75))(terpri)
(write (ffloor 3456 75))(terpri)
(write (fceiling 3456 75))(terpri)
(write (ftruncate 3456 75))(terpri)
(write (fround 3456 75))(terpri)
(write (mod 3456 75))(terpri)
(setq c (complex 6 7))
(write c)(terpri)
(write (complex 5 -9))(terpri)
(write (realpart c))(terpri)
(write (imagpart c))

(print "ax^2+bx+c")
(write ((lambda (a b c x)   (+ (* a (* x x)) (* b x) c))   4 2 9 3))
(print "ax^2-bx+c")
(write ((lambda (a b c x) (+ (-(* a (* x x)) (* b x)) c)) 4 2 9 3))
